### ISSUE TITLE
Add README file about those scripts

### ISSUE THREAD

**Issue by chinesedfan** [HearthSim/extract-scripts#11]
Those scripts are awesome! But could you please to provide a README file of how to use them?

**Comment by jleclanche** [comment]
Sorry, these scripts are really just a dump of bits and pieces we have as part of our pipeline. None of it is officially supported outside of our own stack.

If you have any questions I'll answer them though. Feel free to swing by #hearthsim on freenode.

**Comment by chinesedfan** [comment]
Thanks! I am able to run them now. Just paste my simple tips below.

- With Homebrew, install StormLib first.

```
brew tap homebrew/games
brew install stormlib
```

- With Python 3.4, install the required packages.

```
pip install mpq
pip install hearthstone
```
