### ISSUE TITLE
Also perform proto2 syntax extraction

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/extract-scripts#21]
Using the switch `--proto2` on proto-extractor builds the extracted proto files in proto2 syntax to the target directory. The idea is to push proto3 and proto2 syntax to separate branches. (This also enables us to build hs-proto-go files when a new version is released.)

> Statement about HS proto files [repo hsproto]; When compilation of the proto files is necessary, make sure to CREATE proto files in proto2 syntax with proto-extractor for yourself. The proto2 syntax is necessary to provide accurate default values and force required proto fields on the communication. Compiling and using proto3 syntax IS NOT GUARANTEED TO BE COMPATIBLE with the original client and/or server. For research purposes the proto3 should be sufficient to look at.

**Comment by jleclanche** [comment]
Closing, won't be doing this.
